# Generated by Django 6.0.6 on 2026-08-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_homepagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_secondary_button',
            field=models.CharField(default='Instagram ↗', max_length=80, verbose_name='متن دکمه دوم Hero'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=80, verbose_name='کد داخلی / SKU'),
        ),
    ]
